window.WORLD_CUP_DATA = {
  meta: {
    updatedAt: "2026-06-01T09:00:00+08:00",
    status: "demo",
    note: "2026 World Cup final squads are expected after FIFA's 2026-06-02 submission deadline."
  },
  teams: [
    { group: "A", name: "Mexico", code: "MEX", confederation: "CONCACAF", probability: 4.4, form: "Host", players: [{ name: "Santiago Gimenez", position: "FW", club: "Milan" }, { name: "Edson Alvarez", position: "MF", club: "West Ham" }, { name: "Guillermo Ochoa", position: "GK", club: "TBD" }] },
    { group: "A", name: "South Africa", code: "RSA", confederation: "CAF", probability: 0.8, form: "Balanced", players: [{ name: "Percy Tau", position: "FW", club: "TBD" }, { name: "Ronwen Williams", position: "GK", club: "Mamelodi Sundowns" }] },
    { group: "A", name: "Korea Republic", code: "KOR", confederation: "AFC", probability: 1.8, form: "Fast transition", players: [{ name: "Son Heung-min", position: "FW", club: "Tottenham" }, { name: "Kim Min-jae", position: "DF", club: "Bayern Munich" }] },
    { group: "A", name: "Czechia", code: "CZE", confederation: "UEFA", probability: 1.2, form: "Direct", players: [{ name: "Patrik Schick", position: "FW", club: "Leverkusen" }, { name: "Tomas Soucek", position: "MF", club: "West Ham" }] },
    { group: "B", name: "Canada", code: "CAN", confederation: "CONCACAF", probability: 2.1, form: "Host", players: [{ name: "Alphonso Davies", position: "DF", club: "Bayern Munich" }, { name: "Jonathan David", position: "FW", club: "TBD" }] },
    { group: "B", name: "Bosnia and Herzegovina", code: "BIH", confederation: "UEFA", probability: 0.7, form: "Compact", players: [{ name: "Edin Dzeko", position: "FW", club: "TBD" }, { name: "Sead Kolasinac", position: "DF", club: "Atalanta" }] },
    { group: "B", name: "Qatar", code: "QAT", confederation: "AFC", probability: 0.4, form: "Organized", players: [{ name: "Akram Afif", position: "FW", club: "Al Sadd" }, { name: "Almoez Ali", position: "FW", club: "Al Duhail" }] },
    { group: "B", name: "Switzerland", code: "SUI", confederation: "UEFA", probability: 2.5, form: "Tournament savvy", players: [{ name: "Granit Xhaka", position: "MF", club: "Leverkusen" }, { name: "Manuel Akanji", position: "DF", club: "Manchester City" }] },
    { group: "C", name: "Brazil", code: "BRA", confederation: "CONMEBOL", probability: 13.8, form: "Elite attack", players: [{ name: "Vinicius Junior", position: "FW", club: "Real Madrid" }, { name: "Rodrygo", position: "FW", club: "Real Madrid" }, { name: "Alisson", position: "GK", club: "Liverpool" }] },
    { group: "C", name: "Morocco", code: "MAR", confederation: "CAF", probability: 4.2, form: "High discipline", players: [{ name: "Achraf Hakimi", position: "DF", club: "PSG" }, { name: "Sofyan Amrabat", position: "MF", club: "TBD" }] },
    { group: "C", name: "Haiti", code: "HAI", confederation: "CONCACAF", probability: 0.2, form: "Debut energy", players: [{ name: "Duckens Nazon", position: "FW", club: "TBD" }] },
    { group: "C", name: "Scotland", code: "SCO", confederation: "UEFA", probability: 0.9, form: "Physical", players: [{ name: "Scott McTominay", position: "MF", club: "Napoli" }, { name: "Andy Robertson", position: "DF", club: "Liverpool" }] },
    { group: "D", name: "United States", code: "USA", confederation: "CONCACAF", probability: 5.2, form: "Host", players: [{ name: "Christian Pulisic", position: "FW", club: "Milan" }, { name: "Weston McKennie", position: "MF", club: "Juventus" }, { name: "Antonee Robinson", position: "DF", club: "Fulham" }] },
    { group: "D", name: "Paraguay", code: "PAR", confederation: "CONMEBOL", probability: 1.1, form: "Resilient", players: [{ name: "Miguel Almiron", position: "MF", club: "TBD" }] },
    { group: "D", name: "Australia", code: "AUS", confederation: "AFC", probability: 0.8, form: "Set pieces", players: [{ name: "Mathew Ryan", position: "GK", club: "TBD" }, { name: "Harry Souttar", position: "DF", club: "TBD" }] },
    { group: "D", name: "Turkiye", code: "TUR", confederation: "UEFA", probability: 2.9, form: "Young core", players: [{ name: "Arda Guler", position: "MF", club: "Real Madrid" }, { name: "Hakan Calhanoglu", position: "MF", club: "Inter" }] },
    { group: "E", name: "Germany", code: "GER", confederation: "UEFA", probability: 9.6, form: "Deep squad", players: [{ name: "Florian Wirtz", position: "MF", club: "TBD" }, { name: "Jamal Musiala", position: "MF", club: "Bayern Munich" }, { name: "Antonio Rudiger", position: "DF", club: "Real Madrid" }] },
    { group: "E", name: "Curacao", code: "CUW", confederation: "CONCACAF", probability: 0.1, form: "First appearance", players: [{ name: "Official squad pending", position: "TBD", club: "TBD" }] },
    { group: "E", name: "Cote d'Ivoire", code: "CIV", confederation: "CAF", probability: 1.4, form: "Power", players: [{ name: "Sebastien Haller", position: "FW", club: "TBD" }, { name: "Franck Kessie", position: "MF", club: "Al Ahli" }] },
    { group: "E", name: "Ecuador", code: "ECU", confederation: "CONMEBOL", probability: 2.4, form: "Pressing", players: [{ name: "Moises Caicedo", position: "MF", club: "Chelsea" }, { name: "Piero Hincapie", position: "DF", club: "Leverkusen" }] },
    { group: "F", name: "Netherlands", code: "NED", confederation: "UEFA", probability: 7.7, form: "Control", players: [{ name: "Virgil van Dijk", position: "DF", club: "Liverpool" }, { name: "Cody Gakpo", position: "FW", club: "Liverpool" }, { name: "Frenkie de Jong", position: "MF", club: "Barcelona" }] },
    { group: "F", name: "Japan", code: "JPN", confederation: "AFC", probability: 3.2, form: "Technical", players: [{ name: "Takefusa Kubo", position: "FW", club: "Real Sociedad" }, { name: "Kaoru Mitoma", position: "FW", club: "Brighton" }] },
    { group: "F", name: "Sweden", code: "SWE", confederation: "UEFA", probability: 1.7, form: "Direct", players: [{ name: "Alexander Isak", position: "FW", club: "Newcastle" }, { name: "Dejan Kulusevski", position: "FW", club: "Tottenham" }] },
    { group: "F", name: "Tunisia", code: "TUN", confederation: "CAF", probability: 0.5, form: "Compact", players: [{ name: "Ellyes Skhiri", position: "MF", club: "Eintracht Frankfurt" }] },
    { group: "G", name: "Belgium", code: "BEL", confederation: "UEFA", probability: 4.8, form: "Experienced", players: [{ name: "Kevin De Bruyne", position: "MF", club: "TBD" }, { name: "Jeremy Doku", position: "FW", club: "Manchester City" }] },
    { group: "G", name: "Egypt", code: "EGY", confederation: "CAF", probability: 1.3, form: "Star-led", players: [{ name: "Mohamed Salah", position: "FW", club: "Liverpool" }, { name: "Omar Marmoush", position: "FW", club: "Manchester City" }] },
    { group: "G", name: "IR Iran", code: "IRN", confederation: "AFC", probability: 0.8, form: "Veteran", players: [{ name: "Mehdi Taremi", position: "FW", club: "TBD" }] },
    { group: "G", name: "New Zealand", code: "NZL", confederation: "OFC", probability: 0.2, form: "Underdog", players: [{ name: "Chris Wood", position: "FW", club: "Nottingham Forest" }] },
    { group: "H", name: "Spain", code: "ESP", confederation: "UEFA", probability: 12.5, form: "Possession", players: [{ name: "Lamine Yamal", position: "FW", club: "Barcelona" }, { name: "Pedri", position: "MF", club: "Barcelona" }, { name: "Rodri", position: "MF", club: "Manchester City" }] },
    { group: "H", name: "Cabo Verde", code: "CPV", confederation: "CAF", probability: 0.2, form: "First appearance", players: [{ name: "Official squad pending", position: "TBD", club: "TBD" }] },
    { group: "H", name: "Saudi Arabia", code: "KSA", confederation: "AFC", probability: 0.4, form: "Counter", players: [{ name: "Salem Al-Dawsari", position: "FW", club: "Al Hilal" }] },
    { group: "H", name: "Uruguay", code: "URU", confederation: "CONMEBOL", probability: 5.9, form: "Aggressive", players: [{ name: "Federico Valverde", position: "MF", club: "Real Madrid" }, { name: "Darwin Nunez", position: "FW", club: "Liverpool" }] },
    { group: "I", name: "France", code: "FRA", confederation: "UEFA", probability: 14.6, form: "Complete", players: [{ name: "Kylian Mbappe", position: "FW", club: "Real Madrid" }, { name: "Aurelien Tchouameni", position: "MF", club: "Real Madrid" }, { name: "William Saliba", position: "DF", club: "Arsenal" }] },
    { group: "I", name: "Senegal", code: "SEN", confederation: "CAF", probability: 2.2, form: "Athletic", players: [{ name: "Sadio Mane", position: "FW", club: "Al Nassr" }, { name: "Kalidou Koulibaly", position: "DF", club: "Al Hilal" }] },
    { group: "I", name: "Iraq", code: "IRQ", confederation: "AFC", probability: 0.2, form: "Underdog", players: [{ name: "Official squad pending", position: "TBD", club: "TBD" }] },
    { group: "I", name: "Norway", code: "NOR", confederation: "UEFA", probability: 4.7, form: "Elite forwards", players: [{ name: "Erling Haaland", position: "FW", club: "Manchester City" }, { name: "Martin Odegaard", position: "MF", club: "Arsenal" }] },
    { group: "J", name: "Argentina", code: "ARG", confederation: "CONMEBOL", probability: 11.2, form: "Defending champion", players: [{ name: "Lionel Messi", position: "FW", club: "Inter Miami" }, { name: "Julian Alvarez", position: "FW", club: "Atletico Madrid" }, { name: "Emiliano Martinez", position: "GK", club: "Aston Villa" }] },
    { group: "J", name: "Algeria", code: "ALG", confederation: "CAF", probability: 0.9, form: "Wide threat", players: [{ name: "Riyad Mahrez", position: "FW", club: "Al Ahli" }, { name: "Ismael Bennacer", position: "MF", club: "TBD" }] },
    { group: "J", name: "Austria", code: "AUT", confederation: "UEFA", probability: 2.0, form: "Pressing", players: [{ name: "David Alaba", position: "DF", club: "Real Madrid" }, { name: "Marcel Sabitzer", position: "MF", club: "Dortmund" }] },
    { group: "J", name: "Jordan", code: "JOR", confederation: "AFC", probability: 0.1, form: "First appearance", players: [{ name: "Mousa Al-Taamari", position: "FW", club: "Montpellier" }] },
    { group: "K", name: "Portugal", code: "POR", confederation: "UEFA", probability: 8.8, form: "Creative", players: [{ name: "Cristiano Ronaldo", position: "FW", club: "Al Nassr" }, { name: "Bruno Fernandes", position: "MF", club: "Manchester United" }, { name: "Bernardo Silva", position: "MF", club: "Manchester City" }] },
    { group: "K", name: "Congo DR", code: "COD", confederation: "CAF", probability: 0.4, form: "Physical", players: [{ name: "Yoane Wissa", position: "FW", club: "Brentford" }] },
    { group: "K", name: "Uzbekistan", code: "UZB", confederation: "AFC", probability: 0.2, form: "First appearance", players: [{ name: "Eldor Shomurodov", position: "FW", club: "TBD" }] },
    { group: "K", name: "Colombia", code: "COL", confederation: "CONMEBOL", probability: 3.4, form: "In form", players: [{ name: "Luis Diaz", position: "FW", club: "Liverpool" }, { name: "James Rodriguez", position: "MF", club: "TBD" }] },
    { group: "L", name: "England", code: "ENG", confederation: "UEFA", probability: 10.9, form: "Deep attack", players: [{ name: "Harry Kane", position: "FW", club: "Bayern Munich" }, { name: "Jude Bellingham", position: "MF", club: "Real Madrid" }, { name: "Bukayo Saka", position: "FW", club: "Arsenal" }] },
    { group: "L", name: "Croatia", code: "CRO", confederation: "UEFA", probability: 2.6, form: "Midfield craft", players: [{ name: "Luka Modric", position: "MF", club: "TBD" }, { name: "Josko Gvardiol", position: "DF", club: "Manchester City" }] },
    { group: "L", name: "Ghana", code: "GHA", confederation: "CAF", probability: 0.8, form: "Transition", players: [{ name: "Mohammed Kudus", position: "MF", club: "West Ham" }, { name: "Thomas Partey", position: "MF", club: "TBD" }] },
    { group: "L", name: "Panama", code: "PAN", confederation: "CONCACAF", probability: 0.2, form: "Hard working", players: [{ name: "Anibal Godoy", position: "MF", club: "San Diego FC" }] }
  ],
  mvpCandidates: [
    { name: "Kylian Mbappe", team: "France", position: "FW", rating: 9.4, reason: "法国夺冠概率高，个人终结能力和淘汰赛权重都很突出。" },
    { name: "Vinicius Junior", team: "Brazil", position: "FW", rating: 9.1, reason: "巴西进攻核心之一，边路爆点和关键球能力能显著抬高 MVP 叙事。" },
    { name: "Jude Bellingham", team: "England", position: "MF", rating: 8.9, reason: "英格兰核心中场，进球、推进、对抗和镜头感都足够强。" },
    { name: "Lamine Yamal", team: "Spain", position: "FW", rating: 8.7, reason: "西班牙体系中的创造力焦点，若球队走远会非常吸引投票。" },
    { name: "Lionel Messi", team: "Argentina", position: "FW", rating: 8.4, reason: "卫冕冠军的故事线强，但评分受年龄和出场负荷影响。" }
  ],
  historicalEditions: [
    { year: 1930, host: "Uruguay", champion: "Uruguay", runnerUp: "Argentina", teams: 13, notableSquads: "Uruguay: Jose Nasazzi, Hector Scarone; Argentina: Guillermo Stabile." },
    { year: 1934, host: "Italy", champion: "Italy", runnerUp: "Czechoslovakia", teams: 16, notableSquads: "Italy: Giuseppe Meazza, Luis Monti; Czechoslovakia: Oldrich Nejedly." },
    { year: 1938, host: "France", champion: "Italy", runnerUp: "Hungary", teams: 15, notableSquads: "Italy: Giuseppe Meazza, Silvio Piola; Hungary: Gyorgy Sarosi." },
    { year: 1950, host: "Brazil", champion: "Uruguay", runnerUp: "Brazil", teams: 13, notableSquads: "Uruguay: Obdulio Varela, Alcides Ghiggia; Brazil: Zizinho, Ademir." },
    { year: 1954, host: "Switzerland", champion: "West Germany", runnerUp: "Hungary", teams: 16, notableSquads: "West Germany: Fritz Walter, Helmut Rahn; Hungary: Ferenc Puskas, Sandor Kocsis." },
    { year: 1958, host: "Sweden", champion: "Brazil", runnerUp: "Sweden", teams: 16, notableSquads: "Brazil: Pele, Garrincha, Didi; Sweden: Nils Liedholm." },
    { year: 1962, host: "Chile", champion: "Brazil", runnerUp: "Czechoslovakia", teams: 16, notableSquads: "Brazil: Garrincha, Amarildo; Czechoslovakia: Josef Masopust." },
    { year: 1966, host: "England", champion: "England", runnerUp: "West Germany", teams: 16, notableSquads: "England: Bobby Charlton, Geoff Hurst; West Germany: Franz Beckenbauer." },
    { year: 1970, host: "Mexico", champion: "Brazil", runnerUp: "Italy", teams: 16, notableSquads: "Brazil: Pele, Jairzinho, Tostao, Rivelino; Italy: Gianni Rivera." },
    { year: 1974, host: "West Germany", champion: "West Germany", runnerUp: "Netherlands", teams: 16, notableSquads: "West Germany: Gerd Muller, Franz Beckenbauer; Netherlands: Johan Cruyff." },
    { year: 1978, host: "Argentina", champion: "Argentina", runnerUp: "Netherlands", teams: 16, notableSquads: "Argentina: Mario Kempes, Daniel Passarella; Netherlands: Rob Rensenbrink." },
    { year: 1982, host: "Spain", champion: "Italy", runnerUp: "West Germany", teams: 24, notableSquads: "Italy: Paolo Rossi, Dino Zoff; Brazil: Socrates, Zico; France: Michel Platini." },
    { year: 1986, host: "Mexico", champion: "Argentina", runnerUp: "West Germany", teams: 24, notableSquads: "Argentina: Diego Maradona, Jorge Valdano; England: Gary Lineker." },
    { year: 1990, host: "Italy", champion: "West Germany", runnerUp: "Argentina", teams: 24, notableSquads: "West Germany: Lothar Matthaus, Jurgen Klinsmann; Argentina: Diego Maradona." },
    { year: 1994, host: "United States", champion: "Brazil", runnerUp: "Italy", teams: 24, notableSquads: "Brazil: Romario, Bebeto, Dunga; Italy: Roberto Baggio, Paolo Maldini." },
    { year: 1998, host: "France", champion: "France", runnerUp: "Brazil", teams: 32, notableSquads: "France: Zinedine Zidane, Didier Deschamps; Brazil: Ronaldo, Rivaldo." },
    { year: 2002, host: "Korea/Japan", champion: "Brazil", runnerUp: "Germany", teams: 32, notableSquads: "Brazil: Ronaldo, Rivaldo, Ronaldinho; Germany: Oliver Kahn, Miroslav Klose." },
    { year: 2006, host: "Germany", champion: "Italy", runnerUp: "France", teams: 32, notableSquads: "Italy: Fabio Cannavaro, Andrea Pirlo; France: Zinedine Zidane, Thierry Henry." },
    { year: 2010, host: "South Africa", champion: "Spain", runnerUp: "Netherlands", teams: 32, notableSquads: "Spain: Andres Iniesta, Xavi, Iker Casillas; Netherlands: Wesley Sneijder, Arjen Robben." },
    { year: 2014, host: "Brazil", champion: "Germany", runnerUp: "Argentina", teams: 32, notableSquads: "Germany: Thomas Muller, Manuel Neuer; Argentina: Lionel Messi, Javier Mascherano." },
    { year: 2018, host: "Russia", champion: "France", runnerUp: "Croatia", teams: 32, notableSquads: "France: Kylian Mbappe, Antoine Griezmann; Croatia: Luka Modric, Ivan Rakitic." },
    { year: 2022, host: "Qatar", champion: "Argentina", runnerUp: "France", teams: 32, notableSquads: "Argentina: Lionel Messi, Julian Alvarez, Emiliano Martinez; France: Kylian Mbappe, Antoine Griezmann." }
  ],
  historicalPlayers: [
    { name: "Pele", team: "Brazil", years: "1958, 1962, 1966, 1970", role: "Forward", note: "Three-time World Cup winner." },
    { name: "Diego Maradona", team: "Argentina", years: "1982, 1986, 1990, 1994", role: "Attacking midfielder", note: "1986 Golden Ball and champion." },
    { name: "Ronaldo", team: "Brazil", years: "1994, 1998, 2002, 2006", role: "Forward", note: "2002 champion and Golden Boot." },
    { name: "Miroslav Klose", team: "Germany", years: "2002, 2006, 2010, 2014", role: "Forward", note: "World Cup all-time top scorer." },
    { name: "Zinedine Zidane", team: "France", years: "1998, 2002, 2006", role: "Midfielder", note: "1998 champion, 2006 Golden Ball." },
    { name: "Lionel Messi", team: "Argentina", years: "2006, 2010, 2014, 2018, 2022", role: "Forward", note: "2022 champion, two-time Golden Ball." },
    { name: "Cristiano Ronaldo", team: "Portugal", years: "2006, 2010, 2014, 2018, 2022", role: "Forward", note: "Scored in five World Cups." },
    { name: "Luka Modric", team: "Croatia", years: "2006, 2014, 2018, 2022", role: "Midfielder", note: "2018 Golden Ball, finalist." }
  ]
};

const WORLD_CUP_TEAM_SOURCE = [
  ["MEX", "1", "MX", "Mexico"],
  ["RSA", "2", "ZA", "South Africa"],
  ["KOR", "3", "KR", "South Korea"],
  ["CZE", "4", "CZ", "Czech Republic"],
  ["CAN", "5", "CA", "Canada"],
  ["BIH", "6", "BA", "Bosnia and Herzegovina"],
  ["QAT", "7", "QA", "Qatar"],
  ["SUI", "8", "CH", "Switzerland"],
  ["BRA", "9", "BR", "Brazil"],
  ["MAR", "10", "MA", "Morocco"],
  ["HAI", "11", "HT", "Haiti"],
  ["SCO", "12", "gb-sct", "Scotland"],
  ["USA", "13", "US", "United States"],
  ["PAR", "14", "PY", "Paraguay"],
  ["AUS", "15", "AU", "Australia"],
  ["TUR", "16", "TR", "Turkey"],
  ["GER", "17", "DE", "Germany"],
  ["CUW", "18", "CW", "Curacao"],
  ["CIV", "19", "CI", "Ivory Coast"],
  ["ECU", "20", "EC", "Ecuador"],
  ["NED", "21", "NL", "Netherlands"],
  ["JPN", "22", "JP", "Japan"],
  ["SWE", "23", "SE", "Sweden"],
  ["TUN", "24", "TN", "Tunisia"],
  ["BEL", "25", "BE", "Belgium"],
  ["EGY", "26", "EG", "Egypt"],
  ["IRN", "27", "IR", "Iran"],
  ["NZL", "28", "NZ", "New Zealand"],
  ["ESP", "29", "ES", "Spain"],
  ["CPV", "30", "CV", "Cape Verde"],
  ["KSA", "31", "SA", "Saudi Arabia"],
  ["URU", "32", "UY", "Uruguay"],
  ["FRA", "33", "FR", "France"],
  ["SEN", "34", "SN", "Senegal"],
  ["IRQ", "35", "IQ", "Iraq"],
  ["NOR", "36", "NO", "Norway"],
  ["ARG", "37", "AR", "Argentina"],
  ["ALG", "38", "DZ", "Algeria"],
  ["AUT", "39", "AT", "Austria"],
  ["JOR", "40", "JO", "Jordan"],
  ["POR", "41", "PT", "Portugal"],
  ["COD", "42", "CD", "Democratic Republic of the Congo"],
  ["UZB", "43", "UZ", "Uzbekistan"],
  ["COL", "44", "CO", "Colombia"],
  ["ENG", "45", "gb-eng", "England"],
  ["CRO", "46", "HR", "Croatia"],
  ["GHA", "47", "GH", "Ghana"],
  ["PAN", "48", "PA", "Panama"]
];

const WORLD_CUP_TEAM_SOURCE_BY_CODE = new Map(
  WORLD_CUP_TEAM_SOURCE.map(([code, sourceId, iso2, sourceName]) => [
    code,
    { iso2, sourceId, sourceName }
  ])
);

window.WORLD_CUP_DATA.teams = window.WORLD_CUP_DATA.teams.map((team) => {
  const source = WORLD_CUP_TEAM_SOURCE_BY_CODE.get(team.code);
  if (!source) return team;
  return {
    ...team,
    ...source,
    flag: `https://flagcdn.com/w80/${source.iso2.toLowerCase()}.png`,
    sourceRepository: "https://github.com/rezarahiminia/worldcup2026"
  };
});
