services:
  - type: web
    name: checkfifa
    runtime: node
    plan: free
    branch: master
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: MY_SOLANA_WALLET
        value: EwAh2VbsbgG2xWsFsDYMjmCUqq48cSkms1HATZDi3Vgq
      - key: DEVELOPER_WALLETS
        value: EwAh2VbsbgG2xWsFsDYMjmCUqq48cSkms1HATZDi3Vgq
      - key: SESSION_SECRET
        generateValue: true
      - key: API_FOOTBALL_KEY
        sync: false
